### ISSUE TITLE
Grant Anthony access

### ISSUE THREAD

**Issue by AnthonyAstige** [codeforeauclaire/bikeroutes#1]
@levifelling - Hey can you grant me access to this repo? Thanks~

**Background**
I'm starting to work for this project at https://github.com/AnthonyAstige/bikeroutes. Easier to have write access at this stage with all the little changes than to do pull requests.  Also would like to assign myself issues, add milestones, etc.

**Comment by levifelling** [comment]
@AnthonyAstige I've added you as an admin.
